name: xibe_chat
description: A modern AI chat application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.18
  intl: ^0.18.0
  msix: ^3.16.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

msix_config:
  display_name: Xibe Chat
  publisher_display_name: XibeChat
  identity_name: XibeChat.XibeChat
  msix_version: 1.0.0.0
  logo_path: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  capabilities: internetClient
