name: xibe_chat
description: A modern AI chat application
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.6.18
  markdown: ^7.0.0
  intl: ^0.18.0
  msix: ^3.16.7
  window_manager: ^0.3.7
  image_picker: ^1.0.7
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - logo-nobg.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "logo.png"
  linux:
    generate: true
    image_path: "logo.png"

msix_config:
  display_name: Xibe Chat
  publisher_display_name: XibeChat
  identity_name: XibeChat.XibeChat
  msix_version: 1.0.0.0
  logo_path: logo.png
  capabilities: internetClient
